/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminExportRouteImport } from './routes/admin.export'
import { Route as ApiWaitlistDotcsvRouteImport } from './routes/api.waitlist[.]csv'
import { Route as FeaturesSlugRouteImport } from './routes/features_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExportRoute = AdminExportRouteImport.update({
  id: '/admin/export',
  path: '/admin/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistDotcsvRoute = ApiWaitlistDotcsvRouteImport.update({
  id: '/api/waitlist.csv',
  path: '/api/waitlist.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features_/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/export': typeof AdminExportRoute
  '/api/waitlist.csv': typeof ApiWaitlistDotcsvRoute
  '/features/$slug': typeof FeaturesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/export': typeof AdminExportRoute
  '/api/waitlist.csv': typeof ApiWaitlistDotcsvRoute
  '/features/$slug': typeof FeaturesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/export': typeof AdminExportRoute
  '/api/waitlist.csv': typeof ApiWaitlistDotcsvRoute
  '/features_/$slug': typeof FeaturesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/features'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin/export'
    | '/api/waitlist.csv'
    | '/features/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/features'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin/export'
    | '/api/waitlist.csv'
    | '/features/$slug'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/features'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin/export'
    | '/api/waitlist.csv'
    | '/features_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminExportRoute: typeof AdminExportRoute
  ApiWaitlistDotcsvRoute: typeof ApiWaitlistDotcsvRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/export': {
      id: '/admin/export'
      path: '/admin/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof AdminExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist.csv': {
      id: '/api/waitlist.csv'
      path: '/api/waitlist.csv'
      fullPath: '/api/waitlist.csv'
      preLoaderRoute: typeof ApiWaitlistDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features_/$slug': {
      id: '/features_/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminExportRoute: AdminExportRoute,
  ApiWaitlistDotcsvRoute: ApiWaitlistDotcsvRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
